### ISSUE TITLE
error MSB3073

### ISSUE THREAD

**Issue by nashsclay** [chanan/BlazorStrap#143]
After doing the two install steps from https://blazorstrap.io/, I get this error. It then says to edit _Host.cshtml which I do not have. Is creating one a solution or just implement the includes in the code I already have? Linux 18 Server

![image](https://user-images.githubusercontent.com/6693056/62406305-930a7480-b55e-11e9-88c0-ef38e312d6fe.png)

**Comment by chanan** [comment]
A search online seems to indicate that the issue is with copying the dlls to the bin folder. Are you able to run a plain Server Side Blazor project?

**Comment by nashsclay** [comment]
Negative. This is what I get after cloning the repo

```
root@vultr:/usr/local/bin/BlazorStrap/src/ServerSideSample# dotnet run

Unhandled Exception: System.TypeLoadException: Could not load type 'System.Text.Json.JsonValueType' from assembly 'System.Text.Json, Version=4.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'.
   at Microsoft.Extensions.Configuration.FileConfigurationProvider.HandleException(Exception e)
   at Microsoft.Extensions.Configuration.FileConfigurationProvider.Load(Boolean reload)
   at Microsoft.Extensions.Configuration.FileConfigurationProvider.Load()
   at Microsoft.Extensions.Configuration.ConfigurationRoot..ctor(IList`1 providers)
   at Microsoft.Extensions.Configuration.ConfigurationBuilder.Build()
   at Microsoft.Extensions.Hosting.HostBuilder.BuildAppConfiguration()
   at Microsoft.Extensions.Hosting.HostBuilder.Build()
   at ServerSideSample.Program.Main(String[] args) in /usr/local/bin/BlazorStrap/src/ServerSideSample/Program.cs:line 10
```

**Comment by chanan** [comment]
Do you have AspNetCore core preview7 installed plus the blazor extensions?

**Comment by nashsclay** [comment]
I started to add the dependencies but going deeper and adding more as one dependency relies on another, there is a mess of them. I added a number of the decencies and then it is starting to say that the dependencies were downgrades from the ones I added. Is there not a script that can just add the ones I need?

**Comment by chanan** [comment]
Blazor (server side) is in preview as part of AspNetCore 3 (client side is going be released later). BlazorStrap runs on top of blazor. You need to get blazor running first. Here are the docs from Microsoft on how to do that: https://docs.microsoft.com/en-us/aspnet/core/blazor/get-started?view=aspnetcore-3.0&tabs=visual-studio

Once you do that and get a “blank” blazor project you should be able to run BlazorStrap

**Comment by jbomhold3** [comment]
It says right in the build error items attempting to pull in a preview 6 package. Make sure you have preview 7.. dotnet --version. Clear your nuget cache and should resolve the issue.   @chanan  the blazor extensions plugin is no longer required with p7 and that's a visual studios thing only.

**Comment by nashsclay** [comment]
I cleared the cache, and tried suggestions as above. I had blazor running already. The basic app. I was just trying to get the bootstrap to work properly as the "collapse" function would not work. It looked correct when running the app but just didn't actually collapse when clicked on. This is what my mytestapp.csproj file looks like. Still getting same type of errors of course.

```
<ItemGroup>
    <PackageReference Include="BlazorStrap" Version="1.0.0-preview7-01" />
    <PackageReference Include="bootstrap" Version="4.3.1" />
    <PackageReference Include="Microsoft.AspNetCore.Blazor" Version="3.0.0-preview6.19307.2" />
    <PackageReference Include="Microsoft.AspNetCore.Blazor.Build" Version="3.0.0-preview6.19307.2" PrivateAssets="all" />
    <PackageReference Include="Microsoft.AspNetCore.Blazor.DevServer" Version="3.0.0-preview6.19307.2" PrivateAssets="all" />
    <PackageReference Include="Microsoft.AspNetCore.Components" Version="3.0.0-preview7.19365.7" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="3.0.0-preview7.19362.4" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="3.0.0-preview7.19362.4" />
  </ItemGroup>
```

**Comment by jbomhold3** [comment]
<PackageReference Include="Microsoft.AspNetCore.Blazor" Version="3.0.0-preview7.19365.7" />
    <PackageReference Include="Microsoft.AspNetCore.Blazor.Build" Version="3.0.0-preview7.19365.7" />
    <PackageReference Include="Microsoft.AspNetCore.Blazor.DevServer" Version="3.0.0-preview7.19365.7" />

**Comment by jbomhold3** [comment]
<PackageReference Include="Microsoft.AspNetCore.Blazor" Version="3.0.0-preview7.19365.7" />
    <PackageReference Include="Microsoft.AspNetCore.Blazor.Build" Version="3.0.0-preview7.19365.7" />
    <PackageReference Include="Microsoft.AspNetCore.Blazor.DevServer" Version="3.0.0-preview7.19365.7" />

**Comment by jbomhold3** [comment]
Should be 
  <PackageReference Include="Microsoft.AspNetCore.Blazor" Version="3.0.0-preview7.19365.7" />
    <PackageReference Include="Microsoft.AspNetCore.Blazor.Build" Version="3.0.0-preview7.19365.7" />
    <PackageReference Include="Microsoft.AspNetCore.Blazor.DevServer" Version="3.0.0-preview7.19365.7" />
